# 1. Variáveis de Configuração
CC = g++
CFLAGS = -Wall -Wextra -g
# Flags de aviso e debug (importante!)


# 2. Lista de Arquivos
# Aqui você lista seus arquivos .c manualmente (mais seguro)
SRC = main.cpp
# Magia: Transforma a lista de .c em .o automaticamente
OBJ = $(SRC:.c=.o)

# Nome do executável final
TARGET = cave_explorer

# --- Regras ---

# Regra final: Linkagem
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# Regra Genérica (Pattern Rule): Como transformar qualquer .c em .o
# % é um "coringa" (wildcard).
# $< significa "o arquivo de entrada" (ex: main.c)
# $@ significa "o arquivo de saída" (ex: main.o)
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Limpeza
clean:
	rm -f $(OBJ) $(TARGET)
